# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1131, 662)
        MainWindow.setMinimumSize(QtCore.QSize(1131, 662))
        MainWindow.setMaximumSize(QtCore.QSize(1131, 662))
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Inicio = QtWidgets.QTabWidget(self.centralwidget)
        self.Inicio.setGeometry(QtCore.QRect(10, 10, 471, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Inicio.sizePolicy().hasHeightForWidth())
        self.Inicio.setSizePolicy(sizePolicy)
        self.Inicio.setObjectName("Inicio")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.twConfiguracionSeteada = QtWidgets.QTreeWidget(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.twConfiguracionSeteada.sizePolicy().hasHeightForWidth())
        self.twConfiguracionSeteada.setSizePolicy(sizePolicy)
        self.twConfiguracionSeteada.setMinimumSize(QtCore.QSize(0, 0))
        self.twConfiguracionSeteada.setMaximumSize(QtCore.QSize(3242424, 234242))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.twConfiguracionSeteada.setFont(font)
        self.twConfiguracionSeteada.setAcceptDrops(False)
        self.twConfiguracionSeteada.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.twConfiguracionSeteada.setAutoFillBackground(False)
        self.twConfiguracionSeteada.setStyleSheet("")
        self.twConfiguracionSeteada.setInputMethodHints(QtCore.Qt.ImhNone)
        self.twConfiguracionSeteada.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.twConfiguracionSeteada.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.twConfiguracionSeteada.setMidLineWidth(0)
        self.twConfiguracionSeteada.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.twConfiguracionSeteada.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.twConfiguracionSeteada.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.twConfiguracionSeteada.setAutoScroll(True)
        self.twConfiguracionSeteada.setProperty("showDropIndicator", False)
        self.twConfiguracionSeteada.setUniformRowHeights(True)
        self.twConfiguracionSeteada.setWordWrap(False)
        self.twConfiguracionSeteada.setObjectName("twConfiguracionSeteada")
        self.twConfiguracionSeteada.header().setDefaultSectionSize(200)
        self.twConfiguracionSeteada.header().setMinimumSectionSize(200)
        self.horizontalLayout_3.addWidget(self.twConfiguracionSeteada)
        self.verticalLayout_4.addWidget(self.groupBox_9)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.twAvistamientos = QtWidgets.QTreeWidget(self.groupBox_3)
        self.twAvistamientos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.twAvistamientos.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.twAvistamientos.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.twAvistamientos.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.twAvistamientos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.twAvistamientos.setAutoScroll(True)
        self.twAvistamientos.setProperty("showDropIndicator", False)
        self.twAvistamientos.setAlternatingRowColors(False)
        self.twAvistamientos.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twAvistamientos.setUniformRowHeights(True)
        self.twAvistamientos.setExpandsOnDoubleClick(True)
        self.twAvistamientos.setObjectName("twAvistamientos")
        self.twAvistamientos.header().setCascadingSectionResizes(False)
        self.twAvistamientos.header().setDefaultSectionSize(200)
        self.twAvistamientos.header().setHighlightSections(False)
        self.twAvistamientos.header().setMinimumSectionSize(200)
        self.twAvistamientos.header().setSortIndicatorShown(False)
        self.horizontalLayout_2.addWidget(self.twAvistamientos)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.Inicio.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.layoutWidget = QtWidgets.QWidget(self.tab_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 589))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_8 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_32 = QtWidgets.QLabel(self.groupBox_8)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_7.addWidget(self.label_32)
        self.cbResImagen = QtWidgets.QComboBox(self.groupBox_8)
        self.cbResImagen.setObjectName("cbResImagen")
        self.cbResImagen.addItem("")
        self.cbResImagen.setItemText(0, "")
        self.cbResImagen.addItem("")
        self.cbResImagen.addItem("")
        self.cbResImagen.addItem("")
        self.cbResImagen.addItem("")
        self.cbResImagen.addItem("")
        self.cbResImagen.addItem("")
        self.verticalLayout_7.addWidget(self.cbResImagen)
        self.verticalLayout_17.addLayout(self.verticalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_6.addWidget(self.label_15)
        self.cbResVideo = QtWidgets.QComboBox(self.groupBox_8)
        self.cbResVideo.setObjectName("cbResVideo")
        self.cbResVideo.addItem("")
        self.cbResVideo.setItemText(0, "")
        self.cbResVideo.addItem("")
        self.cbResVideo.addItem("")
        self.cbResVideo.addItem("")
        self.cbResVideo.addItem("")
        self.verticalLayout_6.addWidget(self.cbResVideo)
        self.verticalLayout_17.addLayout(self.verticalLayout_6)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_11.addWidget(self.label_16)
        self.cbNroCapturas = QtWidgets.QComboBox(self.groupBox_8)
        self.cbNroCapturas.setObjectName("cbNroCapturas")
        self.cbNroCapturas.addItem("")
        self.cbNroCapturas.setItemText(0, "")
        self.cbNroCapturas.addItem("")
        self.cbNroCapturas.addItem("")
        self.cbNroCapturas.addItem("")
        self.cbNroCapturas.addItem("")
        self.cbNroCapturas.addItem("")
        self.verticalLayout_11.addWidget(self.cbNroCapturas)
        self.verticalLayout_17.addLayout(self.verticalLayout_11)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_33 = QtWidgets.QLabel(self.groupBox_8)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_9.addWidget(self.label_33)
        self.sbDuracion = QtWidgets.QSpinBox(self.groupBox_8)
        self.sbDuracion.setMinimum(0)
        self.sbDuracion.setMaximum(90)
        self.sbDuracion.setProperty("value", 0)
        self.sbDuracion.setObjectName("sbDuracion")
        self.verticalLayout_9.addWidget(self.sbDuracion)
        self.verticalLayout_17.addLayout(self.verticalLayout_9)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        self.rbLeyenda = QtWidgets.QRadioButton(self.groupBox_8)
        self.rbLeyenda.setObjectName("rbLeyenda")
        self.verticalLayout_18.addWidget(self.rbLeyenda)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_7.addWidget(self.label_17)
        self.leUbicacion = QtWidgets.QLineEdit(self.groupBox_8)
        self.leUbicacion.setText("")
        self.leUbicacion.setObjectName("leUbicacion")
        self.horizontalLayout_7.addWidget(self.leUbicacion)
        self.verticalLayout_18.addLayout(self.horizontalLayout_7)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.verticalLayout_13.addWidget(self.groupBox_8)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.groupBox_7 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.rbFechayhora = QtWidgets.QRadioButton(self.groupBox_7)
        self.rbFechayhora.setObjectName("rbFechayhora")
        self.verticalLayout_12.addWidget(self.rbFechayhora)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_8.addWidget(self.label_21)
        self.deFecha = QtWidgets.QDateEdit(self.groupBox_7)
        self.deFecha.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deFecha.setFont(font)
        self.deFecha.setAutoFillBackground(False)
        self.deFecha.setReadOnly(False)
        self.deFecha.setObjectName("deFecha")
        self.verticalLayout_8.addWidget(self.deFecha)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_10.addWidget(self.label_20)
        self.teHora = QtWidgets.QTimeEdit(self.groupBox_7)
        self.teHora.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.teHora.setFont(font)
        self.teHora.setReadOnly(False)
        self.teHora.setObjectName("teHora")
        self.verticalLayout_10.addWidget(self.teHora)
        self.verticalLayout_12.addLayout(self.verticalLayout_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addWidget(self.groupBox_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem1)
        self.Inicio.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 441, 571))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_37.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_37.setFont(font)
        self.label_37.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_37.setAutoFillBackground(False)
        self.label_37.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_37.setTextFormat(QtCore.Qt.AutoText)
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_37.setWordWrap(True)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_15.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_38.sizePolicy().hasHeightForWidth())
        self.label_38.setSizePolicy(sizePolicy)
        self.label_38.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_38.setAutoFillBackground(False)
        self.label_38.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_38.setTextFormat(QtCore.Qt.AutoText)
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_38.setWordWrap(True)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_15.addWidget(self.label_38)
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_15.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem3)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_39.setFont(font)
        self.label_39.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_39.setAutoFillBackground(False)
        self.label_39.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_39.setTextFormat(QtCore.Qt.AutoText)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_39.setWordWrap(True)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_15.addWidget(self.label_39)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem4)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_44.setFont(font)
        self.label_44.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_44.setAutoFillBackground(False)
        self.label_44.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_44.setTextFormat(QtCore.Qt.AutoText)
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_15.addWidget(self.label_44)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem5)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_45.setFont(font)
        self.label_45.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_45.setAutoFillBackground(False)
        self.label_45.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_45.setTextFormat(QtCore.Qt.AutoText)
        self.label_45.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_45.setWordWrap(True)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_15.addWidget(self.label_45)
        self.verticalLayout_16.addLayout(self.verticalLayout_15)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem6)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_40.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_40.setFont(font)
        self.label_40.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_40.setAutoFillBackground(False)
        self.label_40.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_40.setTextFormat(QtCore.Qt.AutoText)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_40.setWordWrap(True)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_14.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_41.setFont(font)
        self.label_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_41.setAutoFillBackground(False)
        self.label_41.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_41.setTextFormat(QtCore.Qt.AutoText)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_41.setWordWrap(True)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_14.addWidget(self.label_41)
        self.verticalLayout_16.addLayout(self.verticalLayout_14)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem7)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_42 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_42.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_42.setAutoFillBackground(False)
        self.label_42.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_42.setTextFormat(QtCore.Qt.AutoText)
        self.label_42.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_42.setWordWrap(True)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_5.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_43.setAutoFillBackground(False)
        self.label_43.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_43.setTextFormat(QtCore.Qt.AutoText)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_43.setWordWrap(True)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_5.addWidget(self.label_43)
        self.verticalLayout_16.addLayout(self.verticalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_16.addItem(spacerItem9)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.Inicio.addTab(self.tab, "")
        self.gbImagenVivo = QtWidgets.QGroupBox(self.centralwidget)
        self.gbImagenVivo.setGeometry(QtCore.QRect(490, 31, 619, 561))
        self.gbImagenVivo.setAutoFillBackground(True)
        self.gbImagenVivo.setStyleSheet("")
        self.gbImagenVivo.setObjectName("gbImagenVivo")
        self.lbVideo = QtWidgets.QLabel(self.gbImagenVivo)
        self.lbVideo.setGeometry(QtCore.QRect(12, 33, 591, 511))
        self.lbVideo.setAutoFillBackground(False)
        self.lbVideo.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.lbVideo.setText("")
        self.lbVideo.setObjectName("lbVideo")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutWidget6 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.layoutWidget7 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(491, 601, 621, 32))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbEncender = QtWidgets.QPushButton(self.layoutWidget7)
        self.pbEncender.setEnabled(False)
        self.pbEncender.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.pbEncender.setAcceptDrops(False)
        self.pbEncender.setInputMethodHints(QtCore.Qt.ImhNone)
        self.pbEncender.setCheckable(False)
        self.pbEncender.setChecked(False)
        self.pbEncender.setDefault(False)
        self.pbEncender.setObjectName("pbEncender")
        self.horizontalLayout.addWidget(self.pbEncender)
        self.pbCapturas = QtWidgets.QPushButton(self.layoutWidget7)
        self.pbCapturas.setEnabled(True)
        self.pbCapturas.setAutoDefault(False)
        self.pbCapturas.setDefault(False)
        self.pbCapturas.setFlat(False)
        self.pbCapturas.setObjectName("pbCapturas")
        self.horizontalLayout.addWidget(self.pbCapturas)
        self.pbCerrar = QtWidgets.QPushButton(self.layoutWidget7)
        self.pbCerrar.setObjectName("pbCerrar")
        self.horizontalLayout.addWidget(self.pbCerrar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionFecha_y_Hora = QtWidgets.QAction(MainWindow)
        self.actionFecha_y_Hora.setObjectName("actionFecha_y_Hora")
        self.actionC_mara = QtWidgets.QAction(MainWindow)
        self.actionC_mara.setObjectName("actionC_mara")
        self.actionEditar = QtWidgets.QAction(MainWindow)
        self.actionEditar.setObjectName("actionEditar")
        self.actionTama_o_de_ventana = QtWidgets.QAction(MainWindow)
        self.actionTama_o_de_ventana.setObjectName("actionTama_o_de_ventana")
        self.actionFuente = QtWidgets.QAction(MainWindow)
        self.actionFuente.setObjectName("actionFuente")

        self.retranslateUi(MainWindow)
        self.Inicio.setCurrentIndex(1)
        self.pbCerrar.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pbCerrar, self.pbCapturas)
        MainWindow.setTabOrder(self.pbCapturas, self.Inicio)
        MainWindow.setTabOrder(self.Inicio, self.twConfiguracionSeteada)
        MainWindow.setTabOrder(self.twConfiguracionSeteada, self.twAvistamientos)
        MainWindow.setTabOrder(self.twAvistamientos, self.cbResImagen)
        MainWindow.setTabOrder(self.cbResImagen, self.cbResVideo)
        MainWindow.setTabOrder(self.cbResVideo, self.sbDuracion)
        MainWindow.setTabOrder(self.sbDuracion, self.deFecha)
        MainWindow.setTabOrder(self.deFecha, self.teHora)
        MainWindow.setTabOrder(self.teHora, self.pbEncender)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Inicio.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Configuracion establecida"))
        self.twConfiguracionSeteada.headerItem().setText(0, _translate("MainWindow", "Características"))
        self.twConfiguracionSeteada.headerItem().setText(1, _translate("MainWindow", "Valor"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Fecha y horario de avistamientos"))
        self.twAvistamientos.headerItem().setText(0, _translate("MainWindow", "Fecha"))
        self.twAvistamientos.headerItem().setText(1, _translate("MainWindow", "Horario"))
        self.Inicio.setTabText(self.Inicio.indexOf(self.tab_2), _translate("MainWindow", "Inicio"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Cámara"))
        self.label_32.setText(_translate("MainWindow", "Resolución de imagen:"))
        self.cbResImagen.setItemText(1, _translate("MainWindow", "8 MP - 4:3"))
        self.cbResImagen.setItemText(2, _translate("MainWindow", "2 MP - 16:9"))
        self.cbResImagen.setItemText(3, _translate("MainWindow", "2 MP - 4:3"))
        self.cbResImagen.setItemText(4, _translate("MainWindow", "1.5 MP - 16:9"))
        self.cbResImagen.setItemText(5, _translate("MainWindow", "0.9 MP - 16:9"))
        self.cbResImagen.setItemText(6, _translate("MainWindow", "0.3 MP - 4:3"))
        self.label_15.setText(_translate("MainWindow", " Resolucion de video:"))
        self.cbResVideo.setItemText(1, _translate("MainWindow", "1080p - 30fps"))
        self.cbResVideo.setItemText(2, _translate("MainWindow", "720p - 60fps"))
        self.cbResVideo.setItemText(3, _translate("MainWindow", "480p - 60fps"))
        self.cbResVideo.setItemText(4, _translate("MainWindow", "480p - 90fps"))
        self.label_16.setText(_translate("MainWindow", "Cantidad de capturas por detección:"))
        self.cbNroCapturas.setItemText(1, _translate("MainWindow", "1"))
        self.cbNroCapturas.setItemText(2, _translate("MainWindow", "2"))
        self.cbNroCapturas.setItemText(3, _translate("MainWindow", "3"))
        self.cbNroCapturas.setItemText(4, _translate("MainWindow", "4"))
        self.cbNroCapturas.setItemText(5, _translate("MainWindow", "5"))
        self.label_33.setText(_translate("MainWindow", "Tiempo de grabación (segundos):"))
        self.rbLeyenda.setText(_translate("MainWindow", "Leyenda"))
        self.label_17.setText(_translate("MainWindow", "Ubicación del equipo:"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Fecha y Hora de inicio"))
        self.rbFechayhora.setText(_translate("MainWindow", "Seteo manual de fecha y hora"))
        self.label_21.setText(_translate("MainWindow", "Fecha:"))
        self.label_20.setText(_translate("MainWindow", "Hora:"))
        self.Inicio.setTabText(self.Inicio.indexOf(self.tab_4), _translate("MainWindow", "Configuración"))
        self.label_37.setText(_translate("MainWindow", "Pasos para configurar sistema:"))
        self.label_38.setText(_translate("MainWindow", "1) En pestaña Configuración, seleccionar resolución de imagen y video, cantidad de capturas, duración de grabación, leyenda y nombre de la ubicación del equipo, mostrada en la leyenda.                                                                                                                                                                                "))
        self.label.setText(_translate("MainWindow", "En caso de no haber conexión a internet, seleccionar seteo manual y setear hora, la misma se asignará al presionar el boton encender."))
        self.label_39.setText(_translate("MainWindow", "2) Encender sistema."))
        self.label_44.setText(_translate("MainWindow", "La fecha y hora mostrada en configuración indica cuando fue encendido el sistema."))
        self.label_45.setText(_translate("MainWindow", "Para realizar cambios en el funcionamiento del equipo, se requiere cerrar y volver a abrir."))
        self.label_40.setText(_translate("MainWindow", "Boton Capturas y grabaciones:"))
        self.label_41.setText(_translate("MainWindow", "Redirecciona a directorio en el cual se almacenan las capturas y grabaciones realizadas."))
        self.label_42.setText(_translate("MainWindow", "Boton Cerrar:"))
        self.label_43.setText(_translate("MainWindow", "Utilizado para finalizar programa en caso de requerir apagar el equipo o cambiar las resoluciones, duración del video y/o cantidad de capturas por detección."))
        self.Inicio.setTabText(self.Inicio.indexOf(self.tab), _translate("MainWindow", "Ayuda"))
        self.gbImagenVivo.setTitle(_translate("MainWindow", "Imagen en tiempo real"))
        self.pbEncender.setText(_translate("MainWindow", "Encender"))
        self.pbCapturas.setText(_translate("MainWindow", "Capturas y grabaciones"))
        self.pbCerrar.setText(_translate("MainWindow", "Cerrar"))
        self.actionFecha_y_Hora.setText(_translate("MainWindow", "Fecha y Hora"))
        self.actionC_mara.setText(_translate("MainWindow", "Cámara"))
        self.actionEditar.setText(_translate("MainWindow", "Editar"))
        self.actionTama_o_de_ventana.setText(_translate("MainWindow", "Agrandar"))
        self.actionFuente.setText(_translate("MainWindow", "Fuente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

